language: minimal
services:
  - docker
script:
  - docker run -v $PWD/config:/config homeassistant/home-assistant python -m homeassistant --config /config --script check_config --files --info all --secrets
