light.kuchyna_chodbicka:
  hidden: true
light.kuchyna_pri_okne:
  hidden: true
sensor.obyvacka_temperature:
  friendly_name: Teplota
sensor.obyvacka_humidity:
  friendly_name: Vlhkosť
sensor.pocasie_humidity:
  device_class: humidity
