weather:
  name: Pocasie
  entities:
    - sensor.pocasie_humidity
    - sensor.pocasie_pressure
    - sensor.ip_webcam_pressure    
    - sensor.pocasie_temperature
    - sensor.pocasie_wind_speed
camera:
  name: Kamera
  control: hidden
  entities:
    - camera.ip_webcam
    - sensor.ip_webcam_battery_level
    - switch.ip_webcam_video_recording
    - switch.ip_webcam_torch
    - switch.ip_webcam_focus
    - switch.ip_webcam_white_balance_lock
kitchen:
  name: Kuchyna
  entities:
    - sensor.teplota_temperature
    - light.kuchyna
    - light.kuchyna_led
living_room:
  name: Obyvacka
  entities:
    - sensor.obyvacka_temperature
    - sensor.obyvacka_humidity
    - light.obyvacka_lampa
    - light.led_telka
    - light.led_skrinka
zigbee_group:
    view: false
    control: hidden
    name: Zigbee2mqtt
    entities:
      - input_boolean.zigbee_permit_join
      - timer.zigbee_permit_join
      - sensor.zigbee2mqtt_bridge_state
      - switch.zigbee2mqtt_main_join
      - automation.enable_zigbee_joining
      - automation.disable_zigbee_joining
      - automation.disable_zigbee_joining_by_timer
      - input_select.zigbee2mqtt_log_level
      - automation.zigbee2mqtt_log_level


