homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml
  # Double factor authorization
  auth_mfa_modules:
    - type: totp

http:
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Enables support for tracking state changes over time
history:

# Enables the frontend
frontend:

# View all events in a logbook
logbook:

automation: !include automation.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml