homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml
  # Double factor authorization
  auth_mfa_modules:
    - type: totp

http:
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Enables support for tracking state changes over time
history:

# Enables configuration UI
config:

logger:
  default: warn

# Enables the frontend
frontend:

# View all events in a logbook
logbook:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
# Optional, allows Home Assistant developers to focus on popular components.
# include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

weather:
  - platform: darksky
    api_key: !secret darksky_apikey
    mode: daily

influxdb:

automation: !include automation.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml