# homeassistant
name: Home
latitude: 20
longitude: 10
elevation: 150
time_zone: UTC

# http
base_url: https://base-url

# weather
darksky_apikey: some_key

# pushetta
pushettaApiKey: api_key
pushettaChannelName: channel_name

# darksky
darkskyApiKey: api_key

# spotify
spotifyClientId: client_id
spotifyClientSecret: client_secret